name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 13.x, 14.x]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Versions
      run: yarn versions

    - name: Install dependencies
      run: yarn install --frozen-lockfile

    - name: Lint
      run: yarn lint

    - name: Test
      run: yarn jest --ci --silent --reporters=default --reporters=jest-junit

    - name: Audit
      run: yarn audit

    - name: Build
      run: yarn build
